Map<String, String> arabicTranslations = {
  "sign_in": "تسجيل دخول",
  "sign_in_description": "قم بتسجيل الدخول لتصل الي الاف المنتجات",
  "email": "البريد الالكتروني",
  "email_hint": "قم بادخال البريد الالكتروني",
  "password": "كلمه المرور",
  "password_hint": "قم بادخال كلمه المرور",
  "forgot_password": "هل نسيت كلمه المرور؟",
  "don't_have_account": "لا تمتلك حساب ؟ قم بالتسجيل الان",
  "no_internet": "تفقد الاتصال بالانترنت",
  "unknown_error": "حدث خطأ ما! حاول مجددا",
  "sign_up": "انشاء حساب",
  "sign_up_description": "انشئ حساب جديد لتصل الي الاف المنتجات",
  "name": "الاسم",
  "name_hint": "قم بادخال الاسم كامل",
  "username": "اسم المستخدم",
  "username_hint": "قم بادخال اسم المستخدم",
  "confirm_password": "تأكيد كلمه المرور",
  "confirm_password_hint": "قم بادخال كلمه المرور مجددا",
  "continue": "متابعه",
  "have_account": "لديك حساب بالفعل؟ قم بتسجيل الدخول",
  "continue_guest": "متابعه كزائر",
  "phone": "رقم الهاتف",
  "phone_hint": "قم بادخال رقم الهاتف",
  "address": "العنوان",
  "address_hint": "قم بادخال العنوان الخاص بك",
  "skip": "تخطي",
  "choose_image": "اختر مصدر الصوره",
  "camera": "كاميرا",
  "gallery": "معرض الصور",
  "cancel": "الغاء",
  "no_selected_image": "يجب عليك اختيار صوره",
  "invalid_email": "بريد خاطئ",
  "empty_code": "الكود فارغ",
  "confirm_not_match": "كلمه المرور غير متطابقه",
  "short_password": "يجب الا تقل كلمه المرور عن 8 احرف",
  "home": "الرئيسيه",
  "categories": "التصنيفات",
  "favourites": "المفضله",
  "more": "المزيد",
  "invalid_code": "الكود غير صحيح",
  "no_discount_found": "لا يوجد خصم",
  "no_user_found": "لا يوجد مستخدم",
  "price": "@price جنيه",
  "remove": "حذف",
  "coupon_code": "كود خصم",
  "verify": "تحقق",
  "verified": "تم التحقق",
  "order_discount": "سيتم خصم @discount%",
  "cart": "عربه التسوق",
  "empty_cart": "عربه التسوق فارغه , قم بالتسوق الان",
  "total_price": "التكلفه الكليه",
  "checkout": "الدفع",
  "no_categories": "التصنيفات فارغه",
  "change_password": "تغيير كلمه المرور",
  "old_password": "كلمه المرور الحاليه",
  "old_password_hint": "قم بادخال كلمه المرور الحاليه",
  "new_password": "كلمه المرور الجديده",
  "new_password_hint": "قم بادخال كلمه المرور الجديده",
  "save": "حفظ",
  "shipping_address": "عنوان الشحن",
  "city": "المدينه",
  "city_hint": "قم بادخال المدينه",
  "country": "البلد",
  "country_hint": "قم بادخال البلد",
  "postal_code": "الرمز البريدي",
  "postal_code_hint": "قم بادخال الرمز البريدي",
  "payment": "الدفع",
  "card_numbers": "رقم بطاقه الدفع",
  "wrong_card": "قم بادخال ارقام بطاقه الدفع الصحيحه",
  "expiry_date": "تاريخ الانتهاء",
  "month": "الشهر",
  "year": "السنه",
  "previous": "السابق",
  "pay": "ادفع الان",
  "no_favourites": "لا يوجد قائمه مفضله",
  "forgot_password_description": "قم باعادة تعيين كلمه المرور لاستعاده حسابك",
  "code": "كود",
  "code_hint": "قم بادخال الكود الذي وصل اليك",
  "didn't_get_code": "لم يصل اليك الكود؟",
  "send_code": "ارسال الكود",
  "see_all": "عرض الكل",
  "cheapest_products": "ارخص المنتجات",
  "no_products": "لا يوجد منتجات",
  "buy_now": "شراء الان",
  "popular_products": "المنتجات الرائجه",
  "sale": "خصومات",
  "up_to_40": "تصل الي 40%",
  "shop_now": "تسوق الان",
  "welcome": "مرحبا @name",
  "my_account": "حسابي",
  "my_orders": "طلباتي",
  "settings": "الاعدادات",
  "logout": "تسجيل الخروج",
  "order_number": "طلب #@number",
  "no_orders": "لا يوجد طلبات , قم بالتسوق الان",
  "product_out_of_stock": "تم نفاذ الكميه",
  "add_to_cart": "اضف الي عربه التسوق",
  "out_of_stock": "نفذت الكميه",
  "product": "المنتج",
  "reviews": "التقييمات",
  "sizes": "المقاسات",
  "colors": "الالوان",
  "description": "وصف المنتج",
  "rating_based_on": "بناء علي @number تقييم",
  "edit": "تعديل",
  "delete": "حذف",
  "are_you_sure": "هل انت متأكد؟",
  "are_you_sure_review": "هل انت متأكد من حذف هذا التقييم؟",
  "write_a_review": "كتابه تقييم",
  "review_hint": "قم باضافه التقييم الخاص بك",
  "add_review": "اضافه التقييم",
  "no_reviews": "لا يوجد تقييمات , اضف تقييمك الان",
  "settings_changed": "تم حفظ الاعدادات بنجاح",
  "dark": "الوضع الليلي",
  "light": "الوضع النهاري",
  "search_hint": "ما الذي تبحث عنه؟",
  'popular': "الاكثر شعبيه",
  'alphabetically': 'الابجديه',
  'price_high_to_low': 'السعر: الاعلي الي الاقل',
  'price_low_to_high': 'السعر: الاقل الي الاعلي',
  "update_profile": "تحديث البيانات الشخصيه",
  "error_occurred": "حدث خطأ",
  "okay": "حسنا",
  "success": "تم بنجاح",
  "request_cancelled": "تم الغاء الطلب",
  "timeout": "انتهي وقت الاتصال",
};
