Map<String, String> englishTranslations = {
  "sign_in": "Sign in",
  "sign_in_description":
      "Sign in to your account to access thousands of products",
  "email": "Email",
  "email_hint": "Enter your email",
  "password": "Password",
  "password_hint": "Enter your password",
  "forgot_password": "Forgot password?",
  "don't_have_account": "Don't have an account? Register",
  "no_internet": "No Internet Connection",
  "unknown_error": "Something went wrong!",
  "sign_up": "Sign up",
  "sign_up_description": "Create a new account to access thousands of products",
  "name": "Name",
  "name_hint": "Enter your full Name",
  "username": "Username",
  "username_hint": "Enter your username",
  "confirm_password": "Confirm Password",
  "confirm_password_hint": "Enter your password again",
  "continue": "Continue",
  "have_account": "Already have an account? login",
  "continue_guest": "Continue as a guest",
  "phone": "Phone",
  "phone_hint": "Enter your phone number",
  "address": "Address",
  "address_hint": "Enter your address",
  "skip": "Skip",
  "choose_image": "Choose Image Source",
  "camera": "Camera",
  "gallery": "Gallery",
  "cancel": "Cancel",
  "no_selected_image": "You have to choose a picture",
  "invalid_email": "Invalid email",
  "empty_code": "Empty code",
  "confirm_not_match": "Passwords must match",
  "short_password": "Password is too short",
  "home": "Home",
  "categories": "Categories",
  "favourites": "Favourites",
  "more": "More",
  "invalid_code": "Invalid Code",
  "no_discount_found": "No Discount Found",
  "no_user_found": "User not found",
  "price": "@price EGP",
  "remove": "Remove",
  "coupon_code": "Coupon Code",
  "verify": "Verify",
  "verified": "Verified",
  "order_discount": "Your order will be @discount% off",
  "cart": "Cart",
  "empty_cart": "Your Cart is Empty, Start shopping now",
  "total_price": "Total Price",
  "checkout": "Checkout",
  "no_categories": "No Categories Found",
  "change_password": "Change Password",
  "old_password": "Old Password",
  "old_password_hint": "Enter old password",
  "new_password": "New Password",
  "new_password_hint": "Enter new password",
  "save": "Save",
  "shipping_address": "Shipping Address",
  "city": "City",
  "city_hint": "Please enter your city",
  "country": "Country",
  "country_hint": "Please enter your country",
  "postal_code": "Postal Code",
  "postal_code_hint": "Please enter your postal code",
  "payment": "Payment",
  "card_numbers": "Card Numbers",
  "wrong_card": "Please enter correct credit card numbers",
  "expiry_date": "Expiry Date",
  "month": "Month",
  "year": "Year",
  "previous": "Previous",
  "pay": "Pay Now",
  "no_favourites": "No Favourites Found",
  "forgot_password_description":
      "Reset your password to get back to your account",
  "code": "Code",
  "code_hint": "Enter code you received",
  "didn't_get_code": "Didn't receive code?",
  "send_code": "Send Code",
  "see_all": "See All",
  "cheapest_products": "Cheapest Products",
  "no_products": "No Products Found",
  "buy_now": "Buy Now",
  "popular_products": "Popular Products",
  "sale": "Sale",
  "up_to_40": "Up to 40%",
  "shop_now": "Shop Now",
  "welcome": "Welcome @name",
  "my_account": "My Account",
  "my_orders": "My Orders",
  "settings": "Settings",
  "logout": "Logout",
  "order_number": "Order #@number",
  "no_orders": "No Orders found, Start shopping now",
  "product_out_of_stock": "Product is out of stock",
  "add_to_cart": "Add to Cart",
  "out_of_stock": "Out Of Stock",
  "product": "Product",
  "reviews": "Reviews",
  "sizes": "Sizes",
  "colors": "Colors",
  "description": "Description",
  "rating_based_on": "Based on @number reviews",
  "edit": "Edit",
  "delete": "Delete",
  "are_you_sure": "Are you sure?",
  "are_you_sure_review": "Are you sure to delete this review?",
  "write_a_review": "Write a review",
  "review_hint": "Enter your review",
  "add_review": "Add Review",
  "no_reviews": "No Reviews found, Add yours now",
  "settings_changed": "Settings Changed Successfully",
  "dark": "Dark",
  "light": "Light",
  "search_hint": "What are you looking for?",
  'popular': "Popular",
  'alphabetically': 'Alphabetically',
  'price_high_to_low': 'Price: High to Low',
  'price_low_to_high': 'Price: Low to High',
  "update_profile": "Update Profile",
  "error_occurred": "Error Occurred",
  "okay": "Okay",
  "success": "Success",
  "request_cancelled": "request cancelled",
  "timeout": "timeout",
};
